### ISSUE TITLE
[APIGEN] Port

### ISSUE THREAD

**Issue by nicovak** [mathieuancelin/react-workshop#1]
Hello,

It's not a big deal, but all API reference's links are on :9000 in the documentation.

eg: `https://localhost:9000/api/wines/:id`

![Screenshot](http://i.imgur.com/Mf5jHG2.png)

Also, Its should be http and not https.

**Comment by mathieuancelin** [comment]
Hi,

should be fixed with 94b2468106047902f01221f23b4519559dd54213
